server:
  port: 8093

spring:
  application:
    name: ms-exchange-rate-calculate

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true

rest:
  clients:
    default:
      url: http://localhost:8090
    exchange-rate:
      services:
        find-by-currency: /api/exchange-rate/find-by-currency
    exchange-rate-logs:
      services:
        save-log: /api/exchange-rate-logs/create